/*export const ADD_PRODUCT = "ADD_PRODUCT";
export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";*/



export const ADD_BOOKING="ADD_BOOKING";
export const GET_BOOKING="GET_BOOKING";
export const UPDATE_BOOKING="UPDATE_BOOKING";
export const CANCEL_BOOKING="CANCEL_BOOKING";